### ISSUE TITLE
Security patch march 1 subtratum not working 

### ISSUE THREAD

**Issue by nitinxx** [nicholaschum/substratum#172]
Help fast

**Comment by bohrabhijeet** [comment]
Just keep in mind, sending a "Help fast" message doesn't increase the chances of someone answering you. But anyway, 
You need to follow these steps:
Since Google has prevented installation of unauthorized overlays in the March Security patch, you need to follow the following procedure to apply a theme:
- Build and enable all the overlays you need (this won't actually apply overlays)
- Reboot your device
- Go into Manager and select all the overlays you want to enable and from the FAB, select "Enable selected" 
And you're done!

**Comment by nitinxx** [comment]
Very much Thanks for the help ..
