### ISSUE TITLE
Error applying theme

### ISSUE THREAD

**Issue by leonardoaloha** [nicholaschum/substratum#192]
Sorry for my English but ... when applying any theme or overlays i always get an error (debug logchar). I have access to root in both substratum and masquerade. I have the rom octos with nougat 7.1.1

**Comment by leonardoaloha** [comment]
![screenshot_20190103-113002](https://user-images.githubusercontent.com/46351529/50646450-78cad280-0f4c-11e9-8567-567a054e203e.png)
![screenshot_20190103-113900](https://user-images.githubusercontent.com/46351529/50646463-7ff1e080-0f4c-11e9-91f1-180382ce8bc5.png)
This is error

**Comment by androidacy-user** [comment]
I'm afraid nougat has some issues with some overlays... If you can, get a ROM with Oreo or newer. Better overlay support
Otherwise, attempt reinstalling the substratum app. Sometimes helps

If you are rooted or can use Magisk, just use that module 

_Sent from my TETRA using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
