### ISSUE TITLE
Different issue, Nexus 6P No root

### ISSUE THREAD

**Issue by PESauvage** [nicholaschum/substratum#69]
Hi,
So I have a Nexus 6P, on 7.1.2, and not root.
First issue, is that i can't apply a theme, when i click on ok for a rebbot, it does nothing.
And second issue, is that when i rebbot after applying a theme, even if it does nothing, whenn i start again substratum, i have an error message wich says "Autorisation "Super User" refused. Impossible to continue without "Super User" authorisation." ![screenshot_20170307-173516](https://cloud.githubusercontent.com/assets/26255890/23667442/221c4f5a-035e-11e7-818f-86358d16dcf6.png)And the only way to pass this error is to wype the cache of the app.

**Comment by KreAch3R** [comment]
Github "issues" are better utilized for bug reports on the actual code, and not for general user reports.
What you are describing is normal behavior, because there is no AOSP 7.1.2 yet, so that means you are on stock, so that means you need root, which you don't have.

Please visit our community: https://plus.google.com/communities/102261717366580091389, read our guides, and then ask for more help if you need it.

**Comment by xdevs23** [comment]
@KreAch3R Topkek

**Comment by xdevs23** [comment]
Rootless will come tho wont it
