### ISSUE TITLE
Possible fix for bootloop while uninstalling themes in legacy

### ISSUE THREAD

**Issue by ghost** [nicholaschum/substratum#91]
Currently uninstalling framework overlay in legacy roms causes phone to be stuck in infinite boot. This happens with most themes except swift black which only has a placeholder overlay for framework. Interestingly, as long as the placeholder overlay​ is installed, uninstalling other framework overlays does not cause bootloop.

If substratum app itself installs a placeholder framework overlay whenever it detects legacy, it would make a lot of themes run on legacy without issues.

**Comment by nathanchance** [comment]
First off, uninstalling causes bootloops but not installing? What device, Android version, etc because something about that sounds fishy.

Second off,
1. A lot of themes rely on framework to make their themes look good, we can't just override that.
2. We don't provide a ton of support for legacy. Either it works or it doesn't, we don't have control over it. Some themes like the Swift series will provide support for it and it's up to the themers to handle the issues that come of it.

**Comment by ghost** [comment]
Uninstalling causes the issue not installing.
Oxygen OS (all Nougat versions) - OnePlus 3 and 3T

No need to override. Just having a placeholder framework overlay (that doesn't theme anything) fixes this. It is very strange. Multiple overlays can remain installed for framework. If placeholder overlay is installed first, any overlay applied after that would override and theme properly.

Suggestion: when substratum detects legacy, it automatically installs android.placeholder overlay and prompts user to reboot before installing any theme. After reboot the placeholder overlay is hidden from overlays list so it is not uninstalled by mistake. With this, there will be no bootloop while uninstalling any other overlays.


I know that substratum only supports oms and not legacy. Just wanted to bring this to your attention. Feel free to close if it this is not worth investigating. Thanks

**Comment by arvindbadri** [comment]
I have this issue. Uninstalling causes this.
LineageOS on oneplus 3t.

@ungeeked -- is there any way to fix this right now without wiping data?

**Comment by msfjarvis** [comment]
@arvindbadri Flash the substratum rescue zip from /sdcard/substratum/ and if that doesn't work, wipe data.

**Comment by arvindbadri** [comment]
Gonna try dirty flashing the ROM once, and if that doesn't work, wiping data. Sigh. substratum--not even once.

**Comment by AllanWang** [comment]
Just my two cents, but there's clearly more going on with Substratum than just the overlays folder. When the bootloop occurs, it's typically because of a modification to the framework overlay, be it an update or uninstallation. Neither recovery zips help, nor does dirty flashing the rom. The only solution is a clean installation.

**Comment by msfjarvis** [comment]
@AllanWang #122 is a legacy bootloop condition arising from uninstalling overlays including framework and the recovery zips fixed it.

**Comment by AllanWang** [comment]
@MSF-Jarvis still doesn't work for every case though. There are situations where even updating an overlay causes a reboot, so missing files shouldn't be a problem. I've tried the legacy zip before and I've tried manually deleting the files before as well.

It might be worth considering if it's possible to just try catch the issue so that it isn't a problem to begin with. Either way, I've stopped with Substratum on my main phone which has Oxygen OS. This is just a heads up that the problem still exists.

**Comment by KreAch3R** [comment]
@AllanWang

It's not Substratum that's the problem, it's the now( coming O) deprecated RRO2 and the modifications OnePlus has done on top of it (maybe; we don't know because not opensource), because this issue of random bootloops depending on the framework overlay is reported a lot on stock OOS.

So, try-catch what? Our hands are tied for RRO2 (legacy) support. Anyone willing to keep trying to find a way to avoid the bootloop on an unsupported Android OS (we can it unsupported for a reason), that can be implemented by a user app like Substratum can suggest it and we will look into using it.

I don't know if the placeholder framework got a try, @iskandar1023?

**Comment by FAB1150** [comment]
i am facing the same issue.
can someone link me the SubstratumRescue_Legacy.zip file since TWRP doesn't allow me to see the folders (i don't really know why, but putting the files into a USB thumb drive fixes this)?
thanks.

edit: found the file, and it doesn't work. do i really have to do a clean flash of the rom? :(
edit2: wiped everything and it works now. i'm sad for the data but.. better having the phone than the data!

**Comment by nathanchance** [comment]
@FAB1150 https://forum.xda-developers.com/apps/substratum/resource-substratum-rescue-archives-t3652435

Make sure it's that one and if it doesn't work, yes, you will most likely need to clean flash.

**Comment by FAB1150** [comment]
@nathanchance at the end i did a full wipe, and it worked (at the cost of all of my data).
thanks anyways!

**Comment by vaaesh** [comment]
@FAB1150 RIP FAB's data

**Comment by codebucketdev** [comment]
@vaaesh +1

**Comment by msfjarvis** [comment]
Not much can be done about OnePlus's modifications from our end. Closing the issue. Hit me up on telegram if somebody has anything to add to this.
