### ISSUE TITLE
[Suggestion] Icon Pack Support

### ISSUE THREAD

**Issue by leifniem** [nicholaschum/substratum#93]
Might be a bit much to ask, but icon pack support was nice in layers and i had a lot of people nagging me via my developer mail that they "just" want me to add support to like all launchers there are in the world.

So basically just asking if substratum goes full cm theme engine anytime in the future :)

**Comment by KreAch3R** [comment]
It's being worked on, yes. :)

**Comment by akmsk1999** [comment]
@leifniem Maybe substratum launcher??   Like trebuchet.....Or let stock launcher support it🤔

**Comment by Abacate123** [comment]
@akmsk1999 Lol, substratum launcher

**Comment by leifniem** [comment]
@KreAch3R great to hear :) closing this

**Comment by Sykopompos** [comment]
There is already layers like icon support in Substratum, it is just currently hidden because performance aspects of enabling/disabling that many overlays at one time has huge efficiency issues.

As far as full blown cmte like implementation of redirecting the icon without a overlay, it has been discussed but with O right around the corner and the icon changes we have seen, I personally don't want to invest the resources into another icon support method that might get completely depreciated in the next Android version when it looks like we might have a more feasible way to do it with native oem masking support in O

**Comment by leifniem** [comment]
@Sykopompos i agree. I am myself kind of worried about the support for that since icon packs are gonna be a lot harder to work on and likely need to be reworked from scratch i guess.

**Comment by Sykopompos** [comment]
We won't know until we actually get farther along in the developer previews and then get aosp source for O to see what it really implies. 
I doubt we will see a full rework but the code for oem icon masking may be useful for solid native icon packs on Roms

**Comment by nadworny** [comment]
Any progress on this one? Is it still considered?

**Comment by divadsn** [comment]
@nadworny afaik it was abandoned last year.

**Comment by msfjarvis** [comment]
@nadworny this was added and already removed since we didn't like the implementation. It's not being worked on by us anymore and only way it's happening as of now is via a third party sending an acceptable pull request.
